# Generated by Django 2.2.5 on 2019-10-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlendSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Pile ID')),
                ('blend_date', models.DateTimeField(null=True, verbose_name='Date Requested')),
            ],
        ),
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Pile ID')),
                ('rockdescription', models.CharField(choices=[('200', 'Limonite'), ('100', 'Saprolite'), ('0', 'Waste')], max_length=200, null=True, verbose_name='Description')),
                ('kWMT', models.CharField(max_length=200, verbose_name='Weight (kWMT)')),
                ('ni_grade', models.FloatField(default=0, verbose_name='Nickel Grade (%)')),
                ('fe_grade', models.FloatField(default=0, verbose_name='Iron Grade (%)')),
                ('blendsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oreblend.BlendSession')),
            ],
        ),
    ]
